### ISSUE TITLE
when

### ISSUE THREAD

**Issue by fuckyouthinkimboogieman** [czho/obfscmogrfator#1]
when first stuff will be added? :trollface:

**Comment by czho** [comment]
Idk, i started work on it, nothing really done yet, im mostly just reading the source to other obufscators just to get a feel on how they all do stuff.

**Comment by fuckyouthinkimboogieman** [comment]
ok i got it. im just also trying to make an obfuscator so we can merge, yea

**Comment by fuckyouthinkimboogieman** [comment]
but im making it in java, not kotlin. also we was making vortex+ together, so yeh

**Comment by fuckyouthinkimboogieman** [comment]
:p
